// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvbvtS7pzw6jeGtaqELo_QDVvy51R688',
    appId: '1:315615238993:web:21570fdc3481d692f0d170',
    messagingSenderId: '315615238993',
    projectId: 'shoelyapp',
    authDomain: 'shoelyapp.firebaseapp.com',
    storageBucket: 'shoelyapp.appspot.com',
    measurementId: 'G-531NX5Y9VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk6tvkOBcZxFVCenHT_G4CnQMaSrmRQVc',
    appId: '1:315615238993:android:521e62feef42856bf0d170',
    messagingSenderId: '315615238993',
    projectId: 'shoelyapp',
    storageBucket: 'shoelyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzf3JM1R1ru_xyYhruohTOQeuD_Yew70',
    appId: '1:315615238993:ios:79c88851e4379717f0d170',
    messagingSenderId: '315615238993',
    projectId: 'shoelyapp',
    storageBucket: 'shoelyapp.appspot.com',
    iosBundleId: 'com.example.primeTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzf3JM1R1ru_xyYhruohTOQeuD_Yew70',
    appId: '1:315615238993:ios:79c88851e4379717f0d170',
    messagingSenderId: '315615238993',
    projectId: 'shoelyapp',
    storageBucket: 'shoelyapp.appspot.com',
    iosBundleId: 'com.example.primeTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByvbvtS7pzw6jeGtaqELo_QDVvy51R688',
    appId: '1:315615238993:web:c24631aeb0d5d33cf0d170',
    messagingSenderId: '315615238993',
    projectId: 'shoelyapp',
    authDomain: 'shoelyapp.firebaseapp.com',
    storageBucket: 'shoelyapp.appspot.com',
    measurementId: 'G-2X11RJFFFE',
  );
}
